-- Generated by Oracle SQL Developer Data Modeler 4.0.0.833
--   at:        2023-11-12 21:13:34 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE ROL
  (
    ID          INTEGER NOT NULL ,
    DESCRIPCION VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE ROL ADD CONSTRAINT ROL_PK PRIMARY KEY ( ID ) ;

CREATE TABLE USUARIO
  (
    ID        INTEGER NOT NULL ,
    USUARIO   VARCHAR2 (50) NOT NULL ,
    PASSWORD  VARCHAR2 (300) NOT NULL ,
    NOMBRES   VARCHAR2 (90) ,
    APELLIDOS VARCHAR2 (90) ,
    EMAIL     VARCHAR2 (90)
  ) ;
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY ( ID ) ;

CREATE TABLE USUARIO_ROL
  (
    USUARIO_ID INTEGER NOT NULL ,
    ROL_ID     INTEGER NOT NULL
  ) ;
ALTER TABLE USUARIO_ROL ADD CONSTRAINT USUARIO_ROL__IDX PRIMARY KEY ( USUARIO_ID, ROL_ID ) ;

ALTER TABLE USUARIO_ROL ADD CONSTRAINT FK_ASS_1 FOREIGN KEY ( USUARIO_ID ) REFERENCES USUARIO ( ID ) ;

ALTER TABLE USUARIO_ROL ADD CONSTRAINT FK_ASS_2 FOREIGN KEY ( ROL_ID ) REFERENCES ROL ( ID ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              5
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
